### ISSUE TITLE
 Cannot find module './lib/emojify'

### ISSUE THREAD

**Issue by ingadi** [oitozero/gulp-emojify#1]
Hi, First of all love the concept can't wait to use this. Getting this error when I run a task with the plugin. 
![screenshot from 2016-04-10 21 53 20](https://cloud.githubusercontent.com/assets/6121225/14412247/b28a148e-ff66-11e5-9417-bcab1fac9854.png)

**Comment by kingbin** [comment]
Pull-Request #2 should fix the issue. I didn't look to see if anything else was missing.
:heart_eyes_cat:

**Comment by oitozero** [comment]
@kingbin Thx for you PR. 👍
